disabled_rules:
- line_length
- file_length
- function_body_length
- syntactic_sugar
- large_tuple
- cyclomatic_complexity

excluded:

- Pods/
- Library/SweetAlert.swift 

identifier_name:
    excluded:
        - id

